// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wmyazilim.Data;

#nullable disable

namespace wmyazilim.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251224223346_AddProductSlogan")]
    partial class AddProductSlogan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("wmyazilim.Models.DemoRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DemoRequests");
                });

            modelBuilder.Entity("wmyazilim.Models.FooterSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CopyrightText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FooterSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Teknopark İstanbul",
                            CopyrightText = "2025 WMYazılım",
                            Description = "İşletmenizi dijital dünyada bir adım öne taşıyın.",
                            Email = "info@wmyazilim.com",
                            PhoneNumber = "+90 555 000 0000"
                        });
                });

            modelBuilder.Entity("wmyazilim.Models.HeaderMenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HeaderMenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Order = 1,
                            Title = "Anasayfa",
                            Url = "/"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Order = 2,
                            Title = "Fiyatlandırma",
                            Url = "/#pricing"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Order = 3,
                            Title = "Özellikler",
                            Url = "/#features"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Order = 4,
                            Title = "İletişim",
                            Url = "/Home/Contact"
                        });
                });

            modelBuilder.Entity("wmyazilim.Models.HeroSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BadgeIcon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BadgeText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Button1Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Button1Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Button2Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Button2Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HeroSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BadgeIcon = "bi-stars",
                            BadgeText = "Yeni Sürüm Yayında",
                            Button1Text = "Ücretsiz Başla",
                            Button1Url = "/Home/DemoRequest",
                            Button2Text = "Ürünleri Keşfet",
                            Button2Url = "#products",
                            HeroImageUrl = "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80",
                            MainTitle = "İşinizi Dijital Zekayla Büyütün",
                            SubDescription = "WMYazılım ile süreçleri otomatiğe bağlayın."
                        });
                });

            modelBuilder.Entity("wmyazilim.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceYearly")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Slogan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Küçük işletmeler ve startup'lar için ideal.",
                            Features = "Temel E-Ticaret Modülü|Sınırsız Ürün Ekleme|Standart SEO Desteği|E-posta Desteği",
                            ImageUrl = "",
                            IsPopular = false,
                            Price = 499m,
                            PriceYearly = 4990m,
                            Slogan = "",
                            Title = "Başlangıç Paketi"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Büyüyen işletmeler için tam kapsamlı çözüm.",
                            Features = "Gelişmiş E-Ticaret|Pazaryeri Entegrasyonu|Yapay Zeka SEO|7/24 Canlı Destek|Mobil Uygulama (Android)",
                            ImageUrl = "",
                            IsPopular = true,
                            Price = 999m,
                            PriceYearly = 9990m,
                            Slogan = "Yıllık planda 2 ay hediye!",
                            Title = "Profesyonel Paket"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Kurumsal firmalar için özel altyapı.",
                            Features = "Özel Sunucu Altyapısı|Tüm Pazaryerleri|Global SEO Paketi|Özel Müşteri Temsilcisi|iOS ve Android Uygulama|Sınırsız API Erişimi",
                            ImageUrl = "",
                            IsPopular = false,
                            Price = 1999m,
                            PriceYearly = 19990m,
                            Slogan = "%25 İndirim Fırsatı",
                            Title = "Enterprise"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
