// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wmyazilim.Data;

#nullable disable

namespace wmyazilim.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251218135556_AddCreatedDateToDemoRequest")]
    partial class AddCreatedDateToDemoRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("wmyazilim.Models.DemoRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DemoRequests");
                });

            modelBuilder.Entity("wmyazilim.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hızlı ve güvenli online satış altyapısı.",
                            ImageUrl = "https://placehold.co/600x400?text=E-Ticaret",
                            Price = 4999m,
                            Title = "WM E-Ticaret Paketi"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Google sıralamanızı yükselten analiz aracı.",
                            ImageUrl = "https://placehold.co/600x400?text=SEO+Tool",
                            Price = 2499m,
                            Title = "Kurumsal SEO Yazılımı"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sipariş ve stok takibi için profesyonel çözüm.",
                            ImageUrl = "https://placehold.co/600x400?text=Otomasyon",
                            Price = 3500m,
                            Title = "Restoran Otomasyonu"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
